name: Feature Request / Enhancement
description: Suggest an enhancement for mouseless
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest an enhancement for mouseless.
        
  - type: textarea
    attributes:
      label: Problem Description
      description: Please describe the problem that this enhancement would address and/or the benefit it would provide.
      placeholder: ""
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Solution
      description: Please describe the solution you'd like to see, and any alternatives you've considered.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups about the feature request here.
    validations:
      required: false